export const LOGIN_PROGRESS = 'LOGIN_PROGRESS';
export const LOGIN_SUCCESS = 'LOGIN_SUCCESS';
export const LOGIN_FAIL = 'LOGIN_FAIL';

export const FORGOTPASSWORD_PROGRESS = 'FORGOTPASSWORD_PROGRESS';
export const FORGOTPASSWORD_SUCCESS = 'FORGOTPASSWORD_SUCCESS';
export const FORGOTPASSWORD_FAIL = 'FORGOTPASSWORD_FAIL';

export const RESETPASSWORD_PROGRESS = 'RESETPASSWORD_PROGRESS';
export const RESETPASSWORD_SUCCESS = 'RESETPASSWORD_SUCCESS';
export const RESETPASSWORD_FAIL = 'RESETPASSWORD_FAIL';
