export const LOGIN_PROGRESS = 'LOGIN_PROGRESS';
export const LOGIN_SUCCESS = 'LOGIN_SUCCESS';
export const LOGIN_FAIL = 'LOGIN_FAIL';

export const FORGOTPASSWORD_PROGRESS = 'FORGOTPASSWORD_PROGRESS';
export const FORGOTPASSWORD_SUCCESS = 'FORGOTPASSWORD_SUCCESS';
export const FORGOTPASSWORD_FAIL = 'FORGOTPASSWORD_FAIL';

export const RESETPASSWORD_PROGRESS = 'RESETPASSWORD_PROGRESS';
export const RESETPASSWORD_SUCCESS = 'RESETPASSWORD_SUCCESS';
export const RESETPASSWORD_FAIL = 'RESETPASSWORD_FAIL';

export const GETPROJECTTARGET_PROGRESS = 'GETPROJECTTARGET_PROGRESS';
export const GETPROJECTTARGET_SUCCESS = 'GETPROJECTTARGET_SUCESS';
export const GETPROJECTTARGET_FAIL = 'GETPROJECTTARGET_FAIL';

export const FETCH_VENDER_REQUEST = 'FETCH_VENDER_REQUEST';
export const FETCH_VENDER_SUCCESS = 'FETCH_VENDER_SUCCESS';
export const FETCH_VENDER_FAILURE = 'FETCH_VENDER_FAILURE';

export const EDITPROJECTTARGET_PROGRESS = 'EDITPROJECTTARGET_PROGRESS';
export const EDITPROJECTTARGET_SUCCESS = 'EDITPROJECTTARGET_SUCCESS';
export const EDITPROJECTTARGET_FAIL = 'EDITPROJECTTARGET_FAIL';

export const GETRESOURCE_PROGRESS = 'GETRESOURCE_PROGRESS';
export const GETRESOURCE_SUCCESS = 'GETRESOURCE_SUCCESS';
export const GETRESOURCE_FAIL = 'GETRESOURCE_FAIL';

export const ADDPROJECT_PROGRESS = 'ADDPROJECT_PROGRESS';
export const ADDPROJECT_SUCCESS = 'ADDPROJECT_SUCCESS';
export const ADDPROJECT_FAIL = 'ADDPROJECT_FAIL';

export const DELETEPROJECT_PROGRESS = 'DELETEPROJECT_PROGRESS';
export const DELETEPROJECT_SUCCESS = 'DELETEPROJECT_SUCCESS';
export const DELETEPROJECT_FAIL = 'DELETEPROJECT_FAIL';

export const FETCH_RESOURCE_REQUEST = 'FETCH_RESOURCE_REQUEST';
export const FETCH_RESOURCE_SUCCESS = 'FETCH_RESOURCE_SUCCESS';
export const FETCH_RESOURCE_FAILURE = 'FETCH_RESOURCE_FAILURE';

export const DELETE_RESOURCE_REQUEST = 'DELETE_RESOURCE_REQUEST';
export const DELETE_RESOURCE_SUCCESS = 'DELETE_RESOURCE_SUCCESS';
export const DELETE_RESOURCE_FAILURE = 'DELETE_RESOURCE_FAILURE';

export const FETCH_TECHNOLOGY_REQUEST = 'FETCH_TECHNOLOGY_REQUEST';
export const FETCH_TECHNOLOGY_SUCCESS = 'FETCH_TECHNOLOGY_SUCCESS';
export const FETCH_TECHNOLOGY_FAILURE = 'FETCH_TECHNOLOGY_FAILURE';
